### ISSUE TITLE
allow to filter bugs resolved and assigned to

### ISSUE THREAD

**Issue by parkouss** [parkouss/mozbattue#1]
Right know the bugs listed ae not all usefull. On 20, there are 5 that are interesting. So the idea is to be filter bug that are RESOLVED and bugs that are already assigned by default.
Note that we shoul keep all bugs in the local json file (could be useful later for statistics).

As the json data model may change, I think it would be cool to put a version in it. Default behaviour could be that if the json file read has a version < to the version the program is expected, mozbattue should exit and inform the user to update his file.

**Comment by jmaher** [comment]
great summary here- looking forward to this!

**Comment by parkouss** [comment]
I just pushed a few commits that should do the job.

**Comment by jmaher** [comment]
awesome, I will pull and hack!
